---
spring:
  profiles: default

server:
  port: 8105
  

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/  
---
spring:
  profiles: cloud

eureka:
  instance:
    nonSecurePort: 80
    hostname: ${vcap.application.uris[0]}
  client:
    serviceUrl:
      defaultZone: ${vcap.services.eureka.credentials.url}