transaction:
  url: http://MONEY-MOVEMENT-DOMAIN-SERVICES
---
spring:
  profiles: default

server:
  port: 8105
  

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
db:
  userName: ENC(YV+PocsgsO/YIRJwnna8DxEoVbS07/cF)
  password: ENC(U6dIiSC6RT2JzUQ4sifhj63hcw1/rult)         
---
spring:
  profiles: cloud

eureka:
  instance:
    nonSecurePort: 80
    hostname: ${vcap.application.uris[0]}
  client:
    serviceUrl:
      defaultZone: ${vcap.services.eureka.credentials.url}
